### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by agourlay**
The main motivation is having a release of diffson using circe 0.8.0 :bowtie:

### CODE REVIEW

**Comment by satabin** [comment]
Thanks, I will check why the tests fail.

**Comment by satabin** [comment]
@agourlay an you pelase try this work around so that travis build works again: https://github.com/travis-ci/travis-ci/issues/7703

**Comment by agourlay** [comment]
@satabin it works, good find 👍

**Comment by satabin** [comment]
Artifacts published as `2.2.0-SNAPSHOT`. Let me know if you encounter any problem. If there are no problems during the coming week, I will release 2.2.0.

**Comment by agourlay** [comment]
Thank you for the quick reply!

I will play a bit with the snapshot and keep you posted.

**Pull request merged**
