### PR TITLE
Circe support (fix #33)

### LINKED ISSUE #33: Circe Support
[gif-keyboard-14795751616055203746](https://github.com/travisbrown/circe)

### PR DESCRIPTION
**Pull request by guersam**
Added basic circe support. It's copied from my working codebase but it'd be better to have generic test suite for every supported JSON lib.

### CODE REVIEW

**Comment by satabin** [comment]
is it possible to have only the functional change in this PR, not the ones related to sbt and formatting? It would make it easier to understand the change and check that it only adds circe support. Thanks

**Comment by guersam** [comment]
SBT 0.13.5 doesn't work on my machine for some reason so that I had to bump the version before adding actual circe support. Opened #36 to be base of this PR.

**Comment by satabin** [comment]
You can already rebase your branch to remove the sbt update and push it so that travis can check it. I will inspect the other one before this one.

**Comment by guersam** [comment]
Yeah that's another possible option. Anyway it seems that I have to handle the failed coverage check. Opened #37 for further discussion.

**Comment by satabin** [comment]
For the failed coverage test, the short term solution is to add the new package to the packages excluded from coverage as done for playJson currently. I will update the tests so that they are executed for each Json backend once this is merged.

**Comment by guersam** [comment]
Applied your suggestion and rebased.

Actually, in a few days there will be new circe release which depends on cats 0.8 and introduces some breaking changes, so if @emanresusername agrees, I'd prefer waiting for this to having 2.1.0 now.

**Comment by satabin** [comment]
Ok tell me when it’s ready to merge. Thanks for your quick answers to my wishes :)

**Comment by guersam** [comment]
Okay, it is due to a build problem with SBT 0.13.5. I'll 1) open a seperate
PR for build and rebase it onto that one, or I can 2) just remove the first
PR and let CI handle it. Which way would you prefer?

**Comment by satabin** [comment]
@guersam Is your last comment due to a delay in email delivery or did I miss a point?

**Comment by guersam** [comment]
It's the former. Quite long delay....

**Comment by satabin** [comment]
Hi @guersam 

Any news on this?

**Comment by guersam** [comment]
Circe 0.6.0-RC1 is released and 0.6.0 final is waiting for cats supporting Scala 2.12.0 https://github.com/typelevel/cats/pull/1450 and the dependencies are all done.

**Comment by guersam** [comment]
I expect it to come out within this week. Thanks for your patience!

**Comment by guersam** [comment]
And if you want to resolve #39 first I'm totally fine to rework this PR against that.

**Comment by satabin** [comment]
No problem. I am also waiting for some dependencies to be published for 2.12.0. I will work on #39 before.

**Comment by satabin** [comment]
Ok I added support for Scala 2.12 when possible and separated json dialects into several modules. Tests are also now written in such a way that they are run for each dialect. You can rebase and let me know if things are not going well. (see PR #40)

**Comment by guersam** [comment]
Great! I've updated this PR against circe 0.6.0-RC1, will catch up 0.6.0 final as soon as it's released.

**Comment by satabin** [comment]
Awesome, it looks really easy to add a new Json dialect with full test support now :)

**Comment by guersam** [comment]
Updated to circe 0.6.0. :tada:

**Comment by satabin** [comment]
So let’s merge, thanks a lot for this contribution and the improvements to the code base it resulted in :)

**Pull request merged**
