### PR TITLE
dependencies update

### PR DESCRIPTION
**Pull request by agourlay**
contains formatting changes due to scalariform update

I hope the formatting changes are OK for you :)

### CODE REVIEW

**Comment by satabin** [comment]
Still not convinced by closing parenthesis on a new line :) Isn’t that configurable with the new scalariform?

**Comment by agourlay** [comment]
It should be configurable, let me see what I can do!

**Comment by agourlay** [comment]
I think ```.setPreference(DanglingCloseParenthesis, Prevent)``` did the trick

**Comment by satabin** [comment]
Thanks for this.

**Pull request merged**
