### PR TITLE
convert to use play

### PR DESCRIPTION
**Pull request by joprice**

### CODE REVIEW

**Comment by joprice** [comment]
Oops! This was meant to be against my fork.

**Comment by gervaisb** [comment]
@joprice But that is really interesting.
@satabin Could you at least include a link to to [joprice/diffson-play](https://github.com/joprice/diffson-play) ?

**Comment by satabin** [comment]
I already thought about decoupling the underlying json library from the core logic but it is not that straightforward. @joprice maybe you can submit a pull request on the README to mention this fork.

I will investigate how this could be done directly in this repository.

**Comment by joprice** [comment]
Maybe you could use Sangria's marshaling layer as a model http://sangria-graphql.org/learn/#result-marshalling-and-input-unmarshalling.

**Pull request closed without merging**
