### PR TITLE
remove test artifacts from core module

### PR DESCRIPTION
**Pull request by ingarabr**
We don't want to include scalatest and scalacheck in our production code.

### CODE REVIEW

**Comment by satabin** [comment]
Indeed, that makes sense. I will publish new snapshot later today.

**Comment by ingarabr** [comment]
Thanks. 

Do you mind releasing a milestone release (4.0.0-M1)? I'm maintaining a separately released artifact in our own nexus right now. A colleague of mine asked you on gitter but didn't get any response.

**Comment by satabin** [comment]
I can think of having a M1 instead of a snapshot. Sorry for gitter, I missed the notifications, they seem to be disabled.

**Comment by satabin** [comment]
`4.0.0-M1` is now published in Sonatype repositories! Enjoy, and let me know if you experience any problem.

**Pull request merged**
