### PR TITLE
circe: 0.9.0

### PR DESCRIPTION
**Pull request by srp**

### CODE REVIEW

**Comment by satabin** [comment]
Hi, and thanks. Can you please rebase your branch on `v2.2.x` so that it will be included in the next patch version. I already retarget the PR.

**Comment by srp** [comment]
Done, thanks will be awesome to have in the next patch version!

**Comment by fsvehla** [comment]
<3. Can we get a new patch version soon?

**Comment by satabin** [comment]
I am on, it, things are compiling and testing, then I will update to sonatype.

**Comment by satabin** [comment]
Version 2.2.5 released : https://oss.sonatype.org/content/repositories/releases/org/gnieh/diffson-core_2.12/2.2.5/

**Comment by srp** [comment]
Thanks!

**Pull request merged**
